accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('topics.urls')),
]

topics/urls.py
from django.urls import path

from . import views

app_name = 'topics'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

topics/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic,
                              on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self) -> str:
        return f'{self.text[:50]}...'

topics/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('topics:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

topics/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    return render(request, 'topics/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topics/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('topics:index')
    context = {'form': form}
    return render(request, 'topics/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('topics:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'topics/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('topics:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'topics/edit_entry.html', context)
            

topics/templates/topics/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Django Learninglog</title>
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'topics:index' %}">Learning Log</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"data-bs-target="#navbarCollapse" 
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Togle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'topics:topics' %}">Topics</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <span class="navbar-text me-2">Hello, {{ user.username }}</span>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:logout' %}" method='post'>
                            {% csrf_token %}
                            <button name='submit' class="btn btn-outline-secondary btn-sm">Log out</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>

        <main class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
        
    </body>
</html>

topics/templates/topics/edit_entry.html
{% extends 'topics/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Edit Entry.</h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'topics:topic' topic.id %}">{{ topic }}</a>
    </p>

    <p>Edit entry:</p>
    <form action="{% url 'topics:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save changes" %}
    </form>

{% endblock content %}

topics/templates/topics/index.html
{% extends 'topics/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track your learning</h1>
            <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about.
                Whenever you learn something new about a topic, make an entry summarizing what you've learned</p>
            <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

topics/templates/topics/new_entry.html
{% extends 'topics/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add Entry.</h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'topics:topic' topic.id %}">{{ topic }}</a>
    </p>

    <p>Add a new entry:</p>
    <form action="{% url 'topics:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Submit" %}
    </form>

{% endblock content %}

topics/templates/topics/new_topic.html
{% extends 'topics/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add Topic.</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'topics:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add topic" %}
    </form>

{% endblock content %}

topics/templates/topics/topic.html
{% extends 'topics/base.html' %}

{% block page_header %}
    <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'topics:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'topics:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h4>
                <div class="card-body">{{ entry.text|linebreaks }}</div>
            </div>
        {% empty %}
            <li>There are no entries for this topic yer.</li>
        {% endfor %}
{% endblock content %}

topics/templates/topics/topics.html
{% extends 'topics/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul class="list-group border-bottom pb-2 mb-4">
        {% for topic in topics %}
            <li class="list-group-item border-0">
                <a href="{% url 'topics:topic' topic.id %}">{{ topic.text }}</a>
            </li>
        {% empty %}
            <li class="list-group-item border-0">No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'topics:new_topic' %}">Add a new topic</a>

{% endblock content %}